name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies (uv)
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Install Python deps
        run: uv pip install -r requirements.txt
      - name: Run Pyright
        run: uv run pyright app.py || true
      - name: Run tests with coverage
        run: uv run pytest --cov=app --cov-report=term-missing
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
